
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package com.madebyjeffrey;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int PREACH = 22;
  public static final int PLAYA = 37;
  public static final int LINECOMMENT = 7;
  public static final int ONMYLEVEL = 25;
  public static final int TURNUP = 27;
  public static final int LPAREN = 30;
  public static final int REK = 19;
  public static final int DAB = 10;
  public static final int STAR = 43;
  public static final int YOSEWF = 20;
  public static final int RPAREN = 31;
  public static final int AKA = 4;
  public static final int WORDONTHASTREET = 9;
  public static final int BALLOUT = 16;
  public static final int DIGIT = 35;
  public static final int EOF = 0;
  public static final int LIT = 12;
  public static final int THROWMONEY = 15;
  public static final int SUHDUDE = 46;
  public static final int error = 1;
  public static final int DOLLA = 29;
  public static final int NEWLINE = 40;
  public static final int CHECK = 18;
  public static final int OTHERLEVEL = 26;
  public static final int NOTLIT = 13;
  public static final int CUT = 17;
  public static final int DUDESUH = 48;
  public static final int COLON = 34;
  public static final int BOUNCE = 21;
  public static final int NETHING = 39;
  public static final int LETTER = 36;
  public static final int SQUIGGLYSTAR = 5;
  public static final int WEAK = 23;
  public static final int QM = 32;
  public static final int WORDONTHASTREET_LIT = 6;
  public static final int SON = 38;
  public static final int FIRE = 3;
  public static final int PUNC = 45;
  public static final int STREETNAME = 41;
  public static final int FAM = 47;
  public static final int HASHTAG = 33;
  public static final int MIXTAPE = 2;
  public static final int WINNING = 24;
  public static final int AT = 44;
  public static final int BONES = 8;
  public static final int PARTY = 11;
  public static final int GETMONEY = 14;
  public static final int IDENTIFIER = 42;
  public static final int DEAD = 28;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MIXTAPE",
  "FIRE",
  "AKA",
  "SQUIGGLYSTAR",
  "WORDONTHASTREET_LIT",
  "LINECOMMENT",
  "BONES",
  "WORDONTHASTREET",
  "DAB",
  "PARTY",
  "LIT",
  "NOTLIT",
  "GETMONEY",
  "THROWMONEY",
  "BALLOUT",
  "CUT",
  "CHECK",
  "REK",
  "YOSEWF",
  "BOUNCE",
  "PREACH",
  "WEAK",
  "WINNING",
  "ONMYLEVEL",
  "OTHERLEVEL",
  "TURNUP",
  "DEAD",
  "DOLLA",
  "LPAREN",
  "RPAREN",
  "QM",
  "HASHTAG",
  "COLON",
  "DIGIT",
  "LETTER",
  "PLAYA",
  "SON",
  "NETHING",
  "NEWLINE",
  "STREETNAME",
  "IDENTIFIER",
  "STAR",
  "AT",
  "PUNC",
  "SUHDUDE",
  "FAM",
  "DUDESUH"
  };
}

